### ISSUE TITLE
Do you use hardware synchronization techniques in this dataset?

### ISSUE THREAD

**Issue by bzdfzfer** [UTS-CAS/in2laama_datasets#1]
Hi, I want to know whether the datasets are well synchronized or not. If so, could you give me some hints on how to implement that? Thx.

**Comment by clegenti** [comment]
Hi, the datasets are not well synchronised. There is no hardware synchronisation and a classic ubuntu provides the timestamps (through snark for the lidar and ROS for the IMU).

The issue of non real-time data acquisition can easily be observed in the IMU reading: the timestamps are not equally spaced in time. One easy and fairly viable assumption is that the IMU readings are actually collected at a (close to) constant frequency. Based on that assumption, one can therefore interpolate the IMU timestamps using the number of reading and the first and last timestamps.

Overall it is still a challenging set-up that requires handling the asynchronicity in the estimation process.

**Comment by bzdfzfer** [comment]
Thanks for your reply! The interpolation might be a helpful trick for the integration process.
